### ISSUE TITLE
Exception('Missing Palette')

### ISSUE THREAD

**Issue by CommonCoreFun** [katerina7479/pypdflite#14]
Hi there, 
Thanks for pypdflite!
When I try to add png image I get the Exception('Missing Palette'), not sure why. It doesn't happen with any other png file. I edited the original file after the first time I got the exception. It only uses 4 colors and is basically black and white. Any ideas? 
Thanks!

**Comment by katerina7479** [comment]
That's what happens if the program calls the colorspace 'Indexed', but doesn't detect a color pallet saved on the image. If you can, try saving the image to RGB or Grayscale? It may also be that the headers are incorrect for the type of image.
Also, if you can, maybe send me the image? I'm not sure I can do anything to fix it, but I would like to see it as an example.

**Comment by CommonCoreFun** [comment]
I tried both RGB and Grayscale but that didn't work. What *did* work was removing the color profile from the image in Photoshop. Thanks for your help!

**Comment by katerina7479** [comment]
Awesome! I'm glad
