### ISSUE TITLE
center text or image

### ISSUE THREAD

**Issue by ptulpen** [katerina7479/pypdflite#16]
Hello
I use your great library to create a bunch of pdfs.
I wnat to include a series of image with a foot text in the center of the page
The proble is, that they have different width, so I cnnot set the cursor precisely. 
Is there a generic way to center the images and texts?

**Comment by katerina7479** [comment]
So for text, if you use `document.set_justification('center')`, and then use the default cursor to add your text objects, and it will automatically center your text blocks (see the test file JustifyTest for an example).
It's been a while since I worked with this library, it may also center your images as a side-effect, but I think you are better off providing a cursor that is set to the center of the page - 1/2 the width of your image to center your images.

**Comment by ptulpen** [comment]
Thanks, that fixed it. :)
For those who stumbeld accross this post, this is the way I solved it

`  
    from PIL import Image 
[...]
    with Image.open(largeimage) as img:
        width, height = img.size
    
    setheight= 298 - width/2
    document.set_cursor(setheight, 70)
    letter= document.add_image(imagepath+team+"-large.png")
    document.draw_image(letter)
    document.set_font('helvetica', style='R', size=64)

    document.set_cursor(0, 600)
    document.set_justification('center')
    document.add_text( team + " " + str(items[0]))    
        `
